services:
  books-web:
    container_name: books-web
    build:
      dockerfile: /Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - books-db
    environment:
      DB_HOST: books-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: expressdb
      DB_DIALECT: postgres
      ACCESS_TOKEN_KEY: MyAccessTokenKey
      ACCESS_TOKEN_DURATION: 1h
      REFRESH_TOKEN_KEY: MyRefreshTokenKey
      REFRESH_TOKEN_DURATION: 60d
      CONFIRMATION_TOKEN_KEY: MyConfirmationTokenKey
      CONFIRMATION_TOKEN_DURATION: 10d

  books-db:
    container_name: books-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expressdb
    volumes:
      - postgres-data-express:/var/lib/postgresql/data

volumes:
  postgres-data-express:
