apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-auth-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-auth-postgres
  template:
    metadata:
      labels:
        app: library-auth-postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: library-auth-postgres
          image: postgres
          env:
            - name: POSTGRES_DB
              value: auth-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: library
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library
                  key: DB_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
              subPath: postgres/auth
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: "1"
          #   requests:
          #     memory: 256Mi
          #     cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: library-auth-postgres-srv
spec:
  selector:
    app: library-auth-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432