apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-loans-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-loans
  template:
    metadata:
      labels:
        app: library-loans
    spec:
      initContainers:
      - name: wait-for-database
        image: busybox
        command:
        - sh
        - -c
        - until nc -z library-loans-postgres-srv 5432; do sleep 1; done
      - name: wait-for-message-broker
        image: busybox
        command:
        - sh
        - -c
        - until nc -z library-rabbitmq-srv 5672; do sleep 1; done
      containers:
        - name: library-loans
          image: hosnibounechada/library-loans
          env:
            - name: DB_HOST
              value: library-loans-postgres-srv
            - name: DB_PORT
              value: '5432'
            # - name: DB_USER
            #   value: postgres
            # - name: DB_PASSWORD
            #   value: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: library
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library
                  key: DB_PASSWORD
            - name: DB_DATABASE
              value: loans-db
            - name: DB_DIALECT
              value: postgres
            - name: ACCESS_TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: library
                  key: ACCESS_TOKEN_KEY
            - name: ACCESS_TOKEN_DURATION
              value: 1h
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: library
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_URL
              value: amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@library-rabbitmq-srv:5672
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: "1"
          #   requests:
          #     memory: 256Mi
          #     cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: library-loans-srv
spec:
  selector:
    app: library-loans
  ports:
    - name: library-loans
      protocol: TCP
      port: 3000
      targetPort: 3000