name: tests

on:
  pull_request:
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: library-auth-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
      REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
      CONFIRMATION_TOKEN_KEY: ${{ secrets.CONFIRMATION_TOKEN_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install && npm run test:ci
