name: tests

on:
  pull_request:
    paths:
      - "loans/**"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: library-loans-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE_LOANS }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
      ACCESS_TOKEN_DURATION: ${{ secrets.ACCESS_TOKEN_DURATION }}
      REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
      REFRESH_TOKEN_DURATION: ${{ secrets.REFRESH_TOKEN_DURATION }}
      CONFIRMATION_TOKEN_KEY: ${{ secrets.CONFIRMATION_TOKEN_KEY }}
      CONFIRMATION_TOKEN_DURATION: ${{ secrets.CONFIRMATION_TOKEN_DURATION }}
    steps:
      - uses: actions/checkout@v2
      - run: cd loans && npm install && npm run test:ci
